const SEND_VERIFY_REQUEST = "SEND_VERIFY_REQUEST";
const SEND_VERIFY_SUCCESS = "SEND_VERIFY_SUCCESS";
const SEND_VERIFY_FAIL = "SEND_VERIFY_FAIL";
const SEND_VERIFY_RESET = "SEND_VERIFY_RESET";

const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET";

const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET";

const constants = {
    SEND_VERIFY_REQUEST,
    SEND_VERIFY_SUCCESS,
    SEND_VERIFY_FAIL,
    SEND_VERIFY_RESET,

    CHANGE_PASSWORD_REQUEST,
    CHANGE_PASSWORD_SUCCESS,
    CHANGE_PASSWORD_FAIL,
    CHANGE_PASSWORD_RESET,

    FORGOT_PASSWORD_REQUEST,
    FORGOT_PASSWORD_SUCCESS,
    FORGOT_PASSWORD_FAIL,
    FORGOT_PASSWORD_RESET,
};

export default constants;