const BRAND_DETAIL_REQUEST = "BRAND_DETAIL_REQUEST";
const BRAND_DETAIL_SUCCESS = "BRAND_DETAIL_SUCCESS";
const BRAND_DETAIL_FAIL = "BRAND_DETAIL_FAIL";

const BRAND_ALL_REQUEST = "BRAND_ALL_REQUEST";
const BRAND_ALL_SUCCESS = "BRAND_ALL_SUCCESS";
const BRAND_ALL_FAIL = "BRAND_ALL_FAIL";

const BRAND_DELETE_REQUEST = "BRAND_DELETE_REQUEST";
const BRAND_DELETE_SUCCESS = "BRAND_DELETE_SUCCESS";
const BRAND_DELETE_FAIL = "BRAND_DELETE_FAIL";
const BRAND_DELETE_RESET = "BRAND_DELETE_RESET";

const BRAND_UPDATE_REQUEST = "BRAND_UPDATE_REQUEST";
const BRAND_UPDATE_SUCCESS = "BRAND_UPDATE_SUCCESS";
const BRAND_UPDATE_FAIL = "BRAND_UPDATE_FAIL";
const BRAND_UPDATE_RESET = "BRAND_UPDATE_RESET";

const BRAND_CREATE_REQUEST = "BRAND_CREATE_REQUEST";
const BRAND_CREATE_SUCCESS = "BRAND_CREATE_SUCCESS";
const BRAND_CREATE_FAIL = "BRAND_CREATE_FAIL";
const BRAND_CREATE_RESET = "BRAND_CREATE_RESET";

const constants = {
  BRAND_DETAIL_REQUEST,
  BRAND_DETAIL_SUCCESS,
  BRAND_DETAIL_FAIL,

  BRAND_ALL_REQUEST,
  BRAND_ALL_SUCCESS,
  BRAND_ALL_FAIL,

  BRAND_DELETE_REQUEST,
  BRAND_DELETE_SUCCESS,
  BRAND_DELETE_FAIL,
  BRAND_DELETE_RESET,

  BRAND_UPDATE_REQUEST,
  BRAND_UPDATE_SUCCESS,
  BRAND_UPDATE_FAIL,
  BRAND_UPDATE_RESET,

  BRAND_CREATE_REQUEST,
  BRAND_CREATE_SUCCESS,
  BRAND_CREATE_FAIL,
  BRAND_CREATE_RESET,
};

export default constants;
