const CATEGORY_DETAIL_REQUEST = "CATEGORY_DETAIL_REQUEST";
const CATEGORY_DETAIL_SUCCESS = "CATEGORY_DETAIL_SUCCESS";
const CATEGORY_DETAIL_FAIL = "CATEGORY_DETAIL_FAIL";

const CATEGORY_ALL_REQUEST = "CATEGORY_ALL_REQUEST";
const CATEGORY_ALL_SUCCESS = "CATEGORY_ALL_SUCCESS";
const CATEGORY_ALL_FAIL = "CATEGORY_ALL_FAIL";

const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";
const CATEGORY_DELETE_RESET = "CATEGORY_DELETE_RESET";

const CATEGORY_UPDATE_REQUEST = "CATEGORY_UPDATE_REQUEST";
const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
const CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";
const CATEGORY_UPDATE_RESET = "CATEGORY_UPDATE_RESET";

const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL";
const CATEGORY_CREATE_RESET = "CATEGORY_CREATE_RESET";

const constants = {
  CATEGORY_DETAIL_REQUEST,
  CATEGORY_DETAIL_SUCCESS,
  CATEGORY_DETAIL_FAIL,

  CATEGORY_ALL_REQUEST,
  CATEGORY_ALL_SUCCESS,
  CATEGORY_ALL_FAIL,

  CATEGORY_DELETE_REQUEST,
  CATEGORY_DELETE_SUCCESS,
  CATEGORY_DELETE_FAIL,
  CATEGORY_DELETE_RESET,

  CATEGORY_UPDATE_REQUEST,
  CATEGORY_UPDATE_SUCCESS,
  CATEGORY_UPDATE_FAIL,
  CATEGORY_UPDATE_RESET,

  CATEGORY_CREATE_REQUEST,
  CATEGORY_CREATE_SUCCESS,
  CATEGORY_CREATE_FAIL,
  CATEGORY_CREATE_RESET,
};

export default constants;
