const CATELOGY_DETAIL_REQUEST = "CATELOGY_DETAIL_REQUEST";
const CATELOGY_DETAIL_SUCCESS = "CATELOGY_DETAIL_SUCCESS";
const CATELOGY_DETAIL_FAIL = "CATELOGY_DETAIL_FAIL";

const CATELOGY_ALL_REQUEST = "CATELOGY_ALL_REQUEST";
const CATELOGY_ALL_SUCCESS = "CATELOGY_ALL_SUCCESS";
const CATELOGY_ALL_FAIL = "CATELOGY_ALL_FAIL";

const CATELOGY_DELETE_REQUEST = "CATELOGY_DELETE_REQUEST";
const CATELOGY_DELETE_SUCCESS = "CATELOGY_DELETE_SUCCESS";
const CATELOGY_DELETE_FAIL = "CATELOGY_DELETE_FAIL";
const CATELOGY_DELETE_RESET = "CATELOGY_DELETE_RESET";

const CATELOGY_UPDATE_REQUEST = "CATELOGY_UPDATE_REQUEST";
const CATELOGY_UPDATE_SUCCESS = "CATELOGY_UPDATE_SUCCESS";
const CATELOGY_UPDATE_FAIL = "CATELOGY_UPDATE_FAIL";
const CATELOGY_UPDATE_RESET = "CATELOGY_UPDATE_RESET";

const CATELOGY_CREATE_REQUEST = "CATELOGY_CREATE_REQUEST";
const CATELOGY_CREATE_SUCCESS = "CATELOGY_CREATE_SUCCESS";
const CATELOGY_CREATE_FAIL = "CATELOGY_CREATE_FAIL";
const CATELOGY_CREATE_RESET = "CATELOGY_CREATE_RESET";

const constants = {
  CATELOGY_DETAIL_REQUEST,
  CATELOGY_DETAIL_SUCCESS,
  CATELOGY_DETAIL_FAIL,

  CATELOGY_ALL_REQUEST,
  CATELOGY_ALL_SUCCESS,
  CATELOGY_ALL_FAIL,

  CATELOGY_DELETE_REQUEST,
  CATELOGY_DELETE_SUCCESS,
  CATELOGY_DELETE_FAIL,
  CATELOGY_DELETE_RESET,

  CATELOGY_UPDATE_REQUEST,
  CATELOGY_UPDATE_SUCCESS,
  CATELOGY_UPDATE_FAIL,
  CATELOGY_UPDATE_RESET,

  CATELOGY_CREATE_REQUEST,
  CATELOGY_CREATE_SUCCESS,
  CATELOGY_CREATE_FAIL,
  CATELOGY_CREATE_RESET,
};

export default constants;
