const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";

const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST";
const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
const DELETE_IMAGE_FAIL = "DELETE_IMAGE_FAIL";

const UPLOAD_DESCRIPION_REQUEST = "UPLOAD_DESCRIPION_REQUEST";
const UPLOAD_DESCRIPION_SUCCESS = "UPLOAD_DESCRIPION_SUCCESS";
const UPLOAD_DESCRIPION_FAIL = "UPLOAD_DESCRIPION_FAIL";

const DELETE_DESCRIPION_REQUEST = "DELETE_DESCRIPION_REQUEST";
const DELETE_DESCRIPION_SUCCESS = "DELETE_DESCRIPION_SUCCESS";
const DELETE_DESCRIPION_FAIL = "DELETE_DESCRIPION_FAIL";

const constants = {
    UPLOAD_IMAGE_REQUEST,
    UPLOAD_IMAGE_SUCCESS,
    UPLOAD_IMAGE_FAIL,

    DELETE_IMAGE_REQUEST,
    DELETE_IMAGE_SUCCESS,
    DELETE_IMAGE_FAIL,

    UPLOAD_DESCRIPION_REQUEST,
    UPLOAD_DESCRIPION_SUCCESS,
    UPLOAD_DESCRIPION_FAIL,

    DELETE_DESCRIPION_REQUEST,
    DELETE_DESCRIPION_SUCCESS,
    DELETE_DESCRIPION_FAIL,
};

export default constants;